In [2]:
import numpy as np

In [2]:
arr = np.random.randint(1, 10, size=(5, 5))

print(arr)

[[7 5 8 3 5]
 [7 6 8 2 2]
 [9 2 6 3 1]
 [2 2 6 6 9]
 [4 9 7 1 5]]


In [3]:
# 전치

print(arr.T)
print()
print(np.transpose(arr))

[[7 7 9 2 4]
 [5 6 2 2 9]
 [8 8 6 6 7]
 [3 2 3 6 1]
 [5 2 1 9 5]]

[[7 7 9 2 4]
 [5 6 2 2 9]
 [8 8 6 6 7]
 [3 2 3 6 1]
 [5 2 1 9 5]]


In [4]:
# 행렬곱, 내적

print(np.dot(arr.T, arr))

[[199 135 206  78  96]
 [135 150 175  54 102]
 [206 175 249 101 151]
 [ 78  54 101  59  81]
 [ 96 102 151  81 136]]


In [5]:
a = np.arange(6).reshape(2, 3)
print(a, '\n')

y = np.swapaxes(a, 0, 1) # 0은 2차원(열), 1은 1차원(행)
print(y, '\n')

y = a.T
y = np.transpose(a)
print(y)

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 

[[0 3]
 [1 4]
 [2 5]]


In [6]:
# 1 ~ 100 아래와같이 출력 

# [[  1   2   3   4   5   6   7   8   9  10]
#  [ 20  19  18  17  16  15  14  13  12  11]
#  [ 21  22  23  24  25  26  27  28  29  30]
#  [ 40  39  38  37  36  35  34  33  32  31]
#  [ 41  42  43  44  45  46  47  48  49  50]
#  [ 60  59  58  57  56  55  54  53  52  51]
#  [ 61  62  63  64  65  66  67  68  69  70]
#  [ 80  79  78  77  76  75  74  73  72  71]
#  [ 81  82  83  84  85  86  87  88  89  90]
#  [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


arr = np.arange(1, 101).reshape(10,10)
arr
print(arr, type(arr), '\n')

for i in range(10):
    if(i%2!=0):
        arr[i]=arr[i][::-1]
        
print(arr, type(arr))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]] <class 'numpy.ndarray'> 

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


In [7]:
# (0, 1, 2)
# 3차원과 2차원을 바꾸는 경우 : (1, 2, 3) -> (2, 1, 3)

arr = np.arange(6).reshape(1, 2, 3)
print(arr, arr.shape, '\n')

y = np.transpose(arr, (1, 0, 2))
print(y, y.shape, '\n')

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0 1 2]]

 [[3 4 5]]] (2, 1, 3) 



In [8]:
arr = np.arange(6).reshape(1, 2, 3)
print(arr, arr.shape, '\n')

y = np.transpose(arr, (1, 2, 0))
print(y, y.shape)

[[[0 1 2]
  [3 4 5]]] (1, 2, 3) 

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]] (2, 3, 1)


In [9]:
# [과제] 아래배열에서 3차원과 2차원을 변경하여 출력(shape 확인)

arr = np.arange(16).reshape(2, 2, 4)
print(arr, arr.shape, '\n')

y = np.transpose(arr, (1, 0, 2))
print(y, y.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]] (2, 2, 4)


In [17]:
# [과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력(shape 확인)

arr = np.arange(16).reshape(2, 2, 4)
print(arr, arr.shape, '\n')

y = np.transpose(arr, (0, 2, 1))
print(y, y.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]] (2, 4, 2)


In [29]:
arr = np.arange(16).reshape(2, 2, 4)
print(arr, arr.shape, '\n')
arr2 = arr.swapaxes(1, 2) # 두 개의 수만 입력(1차원 2차원)
print(arr2, arr2.shape, '\n')

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 

[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]] (2, 4, 2) 



In [11]:
# 나머지를 구할 경우 사용하는 함수

value1 = np.array([15, 30, 45])
value2 = np.array([2, 7, 9])

print(np.mod(value1, value2))
print(np.remainder(value1, value2))

[1 2 0]
[1 2 0]


In [12]:
# 각 수의 역수를 구해주는 함수

value = np.array([0.85, 1.85, 1, 100])
print(np.reciprocal(value), '\n')

value1 = np.array([100], dtype=int)
print(value1, '\n')
print(np.reciprocal(value1, dtype=float))

[1.17647059 0.54054054 1.         0.01      ] 

[100] 

[0.01]


In [13]:
# 승수의 결과 값을 표시해주는 함수

value1 = np.array([2, 10, 15])
value2 = np.array([1, 2, 3])

print(np.power(value1, 2), '\n')
print(np.power(value1, value2))

[  4 100 225] 

[   2  100 3375]


In [14]:
arr = np.random.randn(10)
# print(arr.mean(), '\n')
# print(arr.std())
arr

array([ 1.25978729,  0.23273387,  0.07388661, -0.62021611,  1.33866129,
       -0.87010621, -1.63338998, -1.99629706,  1.34791998,  0.24778925])

In [15]:
# 양수인 원소의 개수

(arr > 0).sum()

6

In [16]:
# 하나 이상의 값이 True 인지 검사

bools = np.array([False, False, True, True])
bools.any()

True

In [17]:
# 모든 원소가 True인지 검사
bools.all()

False

In [18]:
# 삼항식의 벡터화 버전

arr = np.random.randn(4, 4)
print(arr, '\n')
print(np.where(arr > 0, 2, -2)) # True면 앞, False면 뒤 적용

[[-0.07968836 -1.5786466   0.59814246 -1.02663955]
 [-1.39730672  2.85079152 -0.9360571   0.06676773]
 [ 1.03342592 -0.55567351 -1.20790234 -1.35023439]
 [ 0.1444684   0.48299131  0.02655231 -0.1339494 ]] 

[[-2 -2  2 -2]
 [-2  2 -2  2]
 [ 2 -2 -2 -2]
 [ 2  2  2 -2]]


In [19]:
# arr의 모든 양수를 2로 바꿀 경우
print(np.where(arr>0, 2, arr))

[[-0.07968836 -1.5786466   2.         -1.02663955]
 [-1.39730672  2.         -0.9360571   2.        ]
 [ 2.         -0.55567351 -1.20790234 -1.35023439]
 [ 2.          2.          2.         -0.1339494 ]]


In [20]:
# 두 개의 1차원 배열을 받아서 가능한 모든 (x, y) 짝을 만들 수 있는 2차원 배열 2개 반환

x = np.arange(1, 4)
y = np.arange(1, 4)

xs, ys = np.meshgrid(x, y)
print(xs, '\n')
print(ys)

[[1 2 3]
 [1 2 3]
 [1 2 3]] 

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [21]:
# np.sort()

np.random.seed(0)
arr = np.random.randint(1, 100, size=10)
print(arr, '\n')
print(np.sort(arr), '\n')
print(arr) # 원본 값은 바뀌어있지 않음

[45 48 65 68 68 10 84 22 37 88] 

[10 22 37 45 48 65 68 68 84 88] 

[45 48 65 68 68 10 84 22 37 88]


In [22]:
sorted = np.sort(arr) # sort는 기존 데이터를 바꾸진 않으므로 정렬된 데이터가 필요하다면 따로 저장 필요
print(sorted)

[10 22 37 45 48 65 68 68 84 88]


In [23]:
# 행렬이 2차원 이상일 때 axis 축 값 설정을 통해  행, 열 방향으로 정렬 수행

arr2d = np.array([[8, 12], [7, 1]])
print(arr2d, '\n')
sort_ar2d_axis0 = np.sort(arr2d, axis=0)
print(sort_ar2d_axis0, '\n')
sort_ar2d_axis1 = np.sort(arr2d, axis=1)
print(sort_ar2d_axis1)

[[ 8 12]
 [ 7  1]] 

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


In [24]:
# ndarray.sort(): 원본 반영

np.random.seed(0)
arr = np.random.randint(1, 10, size=10)
print(arr, '\n')
arr.sort() # 정렬 후 원본에 저장
print(arr) # 정렬된 원본 출력

[6 1 4 4 8 4 6 3 5 8] 

[1 3 4 4 4 5 6 6 8 8]


In [25]:
# 다차원 배열의 정렬은 sort 메소드에 넘긴 축에 따라 1차원 부분을 정렬
# 열방향 정렬, default

np.random.seed(0)
arr = np.random.randint(1, 10, size=(5, 3))
print(arr, '\n')
arr.sort(1) # 1 값을 주지 않아도 정렬된 결과값 취득 가능
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[1 4 6]
 [4 4 8]
 [3 5 6]
 [7 8 9]
 [2 7 9]]


In [26]:
# 행방향 정렬, default

np.random.seed(0)
arr = np.random.randint(1, 10, size=(5, 3))
print(arr, '\n')
arr.sort(0)
print(arr)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]
 [9 2 7]] 

[[4 1 4]
 [6 2 4]
 [6 3 5]
 [8 7 7]
 [9 8 9]]


In [52]:
# 정렬된 행렬의 인덱스 반환: 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때

org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)

print(org_array)
print(type(sort_indices))
sort_indices

[3 1 9 5]
<class 'numpy.ndarray'>


array([1, 0, 3, 2], dtype=int64)

In [28]:
# 배열에서 정렬한 후 50% 분위수에 해당하는 원소만 출력

large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.5*len(large_arr))]

0.0017985835409833097

In [53]:
# 배열 집합 연산

names = np.array(['Bob', 'Joe', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [59]:
print(np.sort(np.unique(names)))

['Bob' 'Joe' 'Will']


In [34]:
# 첫 번째 배열의 원소가 두 번째 배열의 원소를 포함하는지 알려ㅈ는 불리언 배열을 반환

values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [60]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식 / .npy 파일로 저장

arr = np.arange(10)
np.save('some_array', arr)

In [61]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
# np.savez: 여러 개의 배열을 압축된 형식으로 저장

np.savez('array_archive.npz', a=arr, b=arr)

In [65]:
arch = np.load('array_archive.npz')

arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# 연습문제 - 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0]을 출력

a = np.ones(10, dtype=int)
for i in range(len(a)):
    if i%2!=0:
        a[i]=0
        
print(a)

[1 0 1 0 1 0 1 0 1 0]


In [75]:
# 연습문제 - np.arange(10)에서 [6, 7, 8, 9] 출력

a = np.arange(10)
print(a[a>5])

[6 7 8 9]


In [86]:
# 연습문제 - a에서 최대값, 최소값 인덱스 출력

a = np.arange(10)
print(a)
print(f'최댓값: {np.argmax(a)}\n최솟값: {np.argmin(a)}')

[0 1 2 3 4 5 6 7 8 9]
최댓값: 9
최솟값: 0


In [87]:
# 연습문제 - a에서 인덱스 배열을 역순으로 출력

np.argsort(a)[::-1]

[9 8 7 6 5 4 3 2 1 0]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int64)

In [92]:
# 연습문제 - np.ones((10, 10))를 아래와 같이 출력

# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

a = np.ones((10, 10))
a[1:9, 1:9]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [49]:
# [도전과제] np.arange(336).reshape(6, 7, 8)에서 100번째 요소의 인덱스

arr = np.arange(336).reshape(6, 7, 8)
# print(arr)
index = []
for i in range(3):
    index.append(np.where(arr == 99)[i][0])
# print(np.where(arr == 99)
print(index)

[1, 5, 3]


In [48]:
arr = np.arange(336).reshape(6,7,8)
# print(arr)
print(np.unravel_index(99,(6,7,8))) # 해당 요소의 인덱스 값을 튜플로 리턴

(1, 5, 3)


In [138]:
# [과제] np.ones((5, 5))를 아래와 같이 출력

# array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 1., 1., 1., 1., 1., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
#        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

a = np.ones((5, 5))
tmp = np.append(np.zeros((2, 5)), a, axis=0)
tmp = np.append(tmp, np.zeros((2, 5)),axis=0)
tmp = np.append(np.zeros((9, 2)), tmp, axis=1)
ret = np.append(tmp, np.zeros((9, 2)), axis=1)

print(ret)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [33]:
a = np.ones((5, 5))
print(np.pad(a, (2, 2)))

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [34]:
a = np.ones((5, 5))
b = np.zeros((9, 9))
b[2:7, 2:7] = a
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [119]:
# [과제] np.zeros((8, 8))를 이용해서 아래와 같이 출력(두 가지 방식: 인덱싱, tile함수)

# array([[0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0]])

a = np.zeros((8,8))
for i in range(len(a)):
    for j in range(len(a)):
        if(i%2!=0):
            if(j%2==0):
                a[i][j]=1
        elif(j%2!=0):
            a[i][j]=1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [38]:
a = np.zeros((8,8))
a[[0,2,4,6]] = [0,1,0,1,0,1,0,1]
a[[1,3,5,7]] = [1,0,1,0,1,0,1,0]
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [41]:
a = np.array([[0,1],[1,0]])
b = np.tile(a,(4,4))
# print(b)
x = np.zeros((8,8))
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [56]:
# [도전과제] np.arange(4)를 이용해서 아래와 같이 출력

# array([[0, 0, 0, 0, 0],
#        [1, 0, 0, 0, 0],
#        [0, 2, 0, 0, 0],
#        [0, 0, 3, 0, 0],
#        [0, 0, 0, 4, 0]])

arr = np.arange(4)
ret = np.diag(arr, -1) # 뒤의 정수가 무엇이냐에 따라 크기가 달라짐(- > 위쪽으로 추가 / + > 왼쪽으로 추가)
for i in range(1, 5):
    for j in range(5):
        if i-1==j:
            ret[i][j]+=1
print(ret)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [50]:
zero = np.zeros((5, 5))
a = np.arange(4)

for i in range(4):
    zero[i + 1, i] = a[i] + 1
    
print(zero)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


[ 파이썬 random 함수 ]

In [193]:
import random

print(random.random(), '\n') # 0.0 <= x < 1.0
print(random.randint(1, 10), '\n') # 1에서 10 사이의 정수 중에서 난수 값
print(random.uniform(10, 20), '\n') # min max 사이 float
print(random.randrange(10), '\n') # 지정 범위 내 int
print(random.choice([1, 2, 3, 4, 5]), '\n') # 리스트 내부에 있는 요소를 랜덤하게 선택

li = [1, 2, 3, 4, 5]
print(random.sample(li, 3), '\n') # 리스트 요소를 중복 없이 3개 리턴
random.shuffle(li) # 리스트 요소를 랜덤하게 섞음
print(li)

0.48027052236111745 

9 

17.863335158369686 

1 

4 

[4, 2, 5] 

[1, 4, 3, 5, 2]


[ numpy random 함수 ]

- np.random.seed: seed를 통한 난수 생성
- np.random.randint: 정수 난수 1개 생성
- np.random.rand: 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn: 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle: 기존 데이터의 순서 바꾸기
- np.random.choice: 기존 데이터에서 sampling

In [194]:
print(np.random.randint(6), '\n') # 0 ~ 5 정수인 난수 1개
print(np.random.randint(1, 20), '\n') # 1 ~ 19 정수인 난수 1개
print(np.random.randint(10, size=10), '\n') # 0 ~ 9 정수인 난수 10개
print(np.random.randint(10, 20, size=10), '\n') # 10 ~ 19 정수인 난수 10개
print(np.random.randint(10, 20, size=(3, 5))) # 10 ~ 19 정수인 난수로 이루어진 3행 5열 배열

2 

5 

[4 3 1 0 6 6 0 9 8 9] 

[15 12 19 18 14 14 10 12 15 17] 

[[17 11 13 12 10]
 [13 12 12 12 13]
 [15 11 17 15 13]]


In [198]:
r = np.random.rand(6) # 0 ~ 1 균일분포
print(r, '\n')
r.mean()

[0.9840303  0.86984807 0.20549913 0.42485264 0.65251435 0.55264587] 



0.6148983924366724

In [200]:
# 표준 정규분포

r= np.random.randn(6)
r.mean()

0.4332623471745383

In [202]:
list = np.arange(1, 6)
print(list)
np.random.shuffle(list)
print(list)

[1 2 3 4 5]
[2 1 4 3 5]


In [211]:
np.random.choice(list)

1

In [213]:
a = np.array([11, 11, 3, 3, 2, 2, 2, 7])
index, count = np.unique(a, return_counts=True)
print(index)
print(count)

[ 2  3  7 11]
[3 2 1 2]


In [214]:
np.random.uniform(1.0, 2.0, 10)

array([1.60093369, 1.46916985, 1.72531623, 1.09765965, 1.11749159,
       1.81322355, 1.10537251, 1.96451082, 1.71263946, 1.52399448])

In [216]:
print(np.random.uniform(0, 1, (2, 3)))

[[0.72685103 0.45714962 0.80221578]
 [0.74353122 0.86629158 0.9274898 ]]


In [215]:
# 0 ~ 1 난수 실수값으로 이루어진 행렬 생성
# uniform 함수의 최소값, 최대값을 각각 0, 1로 지정한 것과 같음(범위 디폴트)

np.random.random_sample((2, 3))

array([[0.88611802, 0.86333012, 0.77542685],
       [0.79729286, 0.78149052, 0.56970604]])

In [217]:
!pip install pandas

In [219]:
ar = np.random.rand(4, 8)
ar

array([[0.14897487, 0.12274482, 0.96391299, 0.30342126, 0.26668018,
        0.7710919 , 0.52831999, 0.87299057],
       [0.99985383, 0.08028484, 0.14307842, 0.94310305, 0.21130156,
        0.04492978, 0.86036206, 0.07357394],
       [0.96184126, 0.76027911, 0.40442232, 0.06511848, 0.7116145 ,
        0.56983421, 0.15138565, 0.62734107],
       [0.65730101, 0.94541895, 0.45783518, 0.51248838, 0.90853832,
        0.24640232, 0.26334652, 0.93011077]])

In [4]:
# 배열을 데이터프레임으로 변환

import pandas as pd

df = pd.DataFrame(ar)
print(df, type(df))

NameError: name 'ar' is not defined

In [228]:
print(df[0])
type(df[0])

0    0.148975
1    0.999854
2    0.961841
3    0.657301
Name: 0, dtype: float64


0         1         2         3         4         5         6  \
0  0.148975  0.122745  0.963913  0.303421  0.266680  0.771092  0.528320   
1  0.999854  0.080285  0.143078  0.943103  0.211302  0.044930  0.860362   
2  0.961841  0.760279  0.404422  0.065118  0.711614  0.569834  0.151386   
3  0.657301  0.945419  0.457835  0.512488  0.908538  0.246402  0.263347   

          7  
0  0.872991  
1  0.073574  
2  0.627341  
3  0.930111

In [226]:
columns = ['id', 'gender', 'age', 'region', 'product', 'price', 'qty', 'time']
index = [np.arange(4)]
df = pd.DataFrame(ar, index, columns=columns)
df

id    gender       age    region   product     price       qty  \
0  0.148975  0.122745  0.963913  0.303421  0.266680  0.771092  0.528320   
1  0.999854  0.080285  0.143078  0.943103  0.211302  0.044930  0.860362   
2  0.961841  0.760279  0.404422  0.065118  0.711614  0.569834  0.151386   
3  0.657301  0.945419  0.457835  0.512488  0.908538  0.246402  0.263347   

       time  
0  0.872991  
1  0.073574  
2  0.627341  
3  0.930111

In [268]:
# 연습문제 - id, gender, age 컬럼에 대하여 의미있는 값으로 변환하여 3개의 컬럼으로 구성된 df를 출력

columns = ['ID', 'Gender', 'Age']
index = [np.arange(1, 4)]

id = np.random.randint(1000, 10000, 3).reshape(3, 1)
gender = np.random.choice(['남', '여'], size=(3, 1))
age = np.random.randint(0, 100, size=(3, 1))

data = np.append(id, gender, axis=1)
data = np.append(data, age, axis=1)

df = pd.DataFrame(data, index, columns=columns)
df

ID Gender Age
1  7668      여  27
2  3945      여   6
3  5618      남   0

In [265]:
h = np.zeros((3, 10))

id = np.random.randint(1, 1000, size=(1, 10))
gender = np.random.randint(2, size=(1, 10))
age = np.random.randint(0, 120, size=(1, 10))

h[0]=id
h[1]=gender
h[2]=age

h=np.transpose(h)

columns = ['id', 'gender', 'age']
index = np.arange(1, 11)
df = pd.DataFrame(h, index, columns = columns)

df

id  gender    age
1   646.0     1.0   39.0
2    60.0     1.0   79.0
3   977.0     0.0   13.0
4   475.0     0.0   35.0
5   446.0     1.0  102.0
6   800.0     1.0   11.0
7   967.0     0.0  103.0
8   346.0     0.0   75.0
9   204.0     0.0  112.0
10  658.0     0.0   54.0

In [278]:
ar = np.zeros((4, 3))
columns = ['ID', 'Gender', 'Age']
index = [np.arange(1, 5)]

df = pd.DataFrame(ar, index, columns=columns)
df.ID = np.random.randint(1000, 10000, 4)
df.Gender = np.random.choice(['M', 'F'], 4)
df.Age = np.random.randint(1, 100, 4)
df

ID Gender  Age
1  8152      F   32
2  7238      F   84
3  8632      M   67
4  8445      M   20

In [318]:
# [과제] 고객 구매데이터 생성(id, 성별, 연령, 지역, 상품, 가격, 구매시간) 후 데이터프레임 변환

arr = np.zeros((5, 7))
columns = ['ID', 'Gender', 'Age', 'Region', 'Product', 'Price', 'Time']
index = [np.arange(1, 6)]

df = pd.DataFrame(arr, index, columns=columns)
df.ID = np.random.randint(1000, 10000, 5)
df.Gender = np.random.choice(['M', 'F'], 5)
df.Age = np.random.randint(1, 100, 5)
df.Region = np.random.choice(['서울', '인천', '대전', '대구', '부산', '울산'], 5)
df.Product = np.random.choice(['식료품', '청소용품', '사무용폼', '생활용품', '의류'], 5)
df.Price = np.random.randint(10, 1000, 5)*100
df.Time = np.random.randint(10, 24, 5)
df


ID Gender  Age Region Product  Price  Time
1  4362      F   93     울산    청소용품  57100    19
2  9797      M   86     울산     식료품  28300    18
3  6869      F   88     서울    사무용폼  31500    19
4  3018      M   38     대전      의류   9900    13
5  4867      M   21     인천    청소용품  48100    20

[과제] 아래 가이드에 따라 고객 구매데이터를 생성하고 데이터프레임으로 변환하여 출력(관측치 1000개)
- id: 1~1000 일련번호
- gender: 0, 1  정수 난수
- age: 0~80 정수 난수
- region: 1~10 정수 난수
- product_19: 1000~50000 실수 난수
- product_20: 1000~50000 실수 난수
- quantity_19: 1~100 정수 난수
- quantity_20: 1~100 정수 난수
- time_19: 01~24 정수 난수
- time_20: 01~24 정수 난수
- amount_19: price_19 * quantity_19
- amount_20: price_20 * quantity_20
- sales: 19년 대비 구매 증가면 1, 감소면 0

In [90]:
import warnings

warnings.filterwarnings('ignore')

sample=10000

col = ['ID', 'Gender', 'Age', 'Region', 'Product', 'Price', 'Quantity_19', 'Quantity_20',
           'Time_19', 'Time_20', 'Amount_19', 'Amount_20', 'Sales']
arr = np.zeros((sample, len(col)))
index = [np.arange(1, sample+1)]

df = pd.DataFrame(arr, index, columns=col)
df.ID = np.random.randint(1, 1000, sample)
df.Gender = np.random.choice(['M', 'F'], sample)
df.Age = np.random.randint(10, 81, sample)
df.Region = np.random.choice(['서울', '부산', '인천', '대구', '대전', '광주', '울산', '세종', '경기', '제주'], sample)
df.Product = np.random.randint(111, 222, sample)

pricearray= np.random.randint(10, 500, size = 100000)*100
for i in range(1,customer+1):
    df.Price[i] = pricearray[df.Product[i]]

df.Price = np.random.randint(10,501,sample)*100
df.Quantity_19 = np.random.randint(1, 101, sample)
df.Quantity_20 = np.random.randint(1, 101, sample)

df.Time_19 = np.random.randint(1, 25, sample)
df.Time_20 = np.random.randint(1, 25, sample)
df.Amount_19 = df.Price * df.Quantity_19
df.Amount_20 = df.Price * df.Quantity_20

df.Sales = np.where(df.Amount_20>df.Amount_19, '구매 증가', '구매 감소')
# for i in range(1, sample+1):
#     if df.Amount_20[i]>df.Amount_19[i]:
#         df.Sales[i]='구매 증가'
#     elif df.Amount_20[i]<df.Amount_19[i]:
#         df.Sales[i]='구매 감소'
#     else:
#         df.Sales[i]='현상 유지'
df


ID Gender  Age Region  Product  Price  Quantity_19  Quantity_20  \
1      803      M   80     대전      123  44100           85           61   
2      571      M   71     서울      187  31300            4           92   
3      131      M   74     경기      128  10900           15           51   
4      892      M   38     제주      188  49800            3           51   
5      402      M   21     부산      178  15900           94           37   
...    ...    ...  ...    ...      ...    ...          ...          ...   
9996   769      F   43     광주      164   7700          100           51   
9997   162      F   49     부산      210  20900           52            7   
9998   799      M   74     인천      151  29500           22           48   
9999   929      M   52     광주      198  42600           51           83   
10000  627      M   66     경기      116  24600           73           77   

       Time_19  Time_20  Amount_19  Amount_20  Sales  
1            4       23    3748500    2690100  구매 감소  
2           21       24     125200    2879600  구매 증가  
3           17       24     163500     555900  구매 증가  
4           24        2     149400    2539800  구매 증가  
5           11       17    1494600     588300  구매 감소  
...        ...      ...        ...        ...    ...  
9996         6        9     770000     392700  구매 감소  
9997        13        9    1086800     146300  구매 감소  
9998         4        1     649000    1416000  구매 증가  
9999        17        6    2172600    3535800  구매 증가  
10000       15       15    1795800    1894200  구매 증가  

[10000 rows x 13 columns]

In [80]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

customer = 1000

array = np.zeros((customer,14),dtype = int)
df = pd.DataFrame(array,(np.arange(1,customer+1)),columns = ['id','gender','age','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales'])
np.random.seed(0)
df.id = np.arange(1,customer+1)
df.gender = np.random.choice(['M','F'],customer)
df.age = np.random.randint(1,81,size=customer)
df.product_19 = np.random.randint(11111,100000,size = customer)
df.product_20 = np.random.randint(11111,100000,size = customer)

pricearray= np.random.randint(10,500,size = 100000)*100

for i in range(1,customer+1):
    df.price_19[i] = pricearray[df.product_19[i]]
    df.price_20[i] = pricearray[df.product_20[i]]

df.quantity_19 = np.random.randint(1,101,size = customer)
df.quantity_20 = np.random.randint(1,101,size = customer)

df.time_19 = np.random.randint(1,25,size = customer)
df.time_20 = np.random.randint(1,25,size = customer)

df.amount_19 = df.price_19*df.quantity_19
df.amount_20 = df.price_20*df.quantity_20

for i in range(1,customer+1):
    if df.amount_20[i]>df.amount_19[i]:
        df.sales[i] = 1
    else:
        df.sales[i] = 0

df

id gender  age  product_19  product_20  price_19  price_20  \
1        1      M   40       24227       55976     42900     17000   
2        2      F   29       77462       78920     27400     38500   
3        3      F   25       53750       46507     25600     49500   
4        4      M   19       73611       29381     28000     19100   
5        5      F   68       82728       84075      1300     23200   
...    ...    ...  ...         ...         ...       ...       ...   
996    996      M   24       73435       97517      6400     21300   
997    997      M   53       36781       83820     34400     21600   
998    998      M   24       38495       96299     12700      7700   
999    999      F   73       56675       61737     15700     21000   
1000  1000      M   42       88153       76382     10100     32500   

      quantity_19  quantity_20  time_19  time_20  amount_19  amount_20  sales  
1              76           79       18       20    3260400    1343000      0  
2              66           45        4       19    1808400    1732500      0  
3              55           36       24       18    1408000    1782000      1  
4              71           15        2       17    1988000     286500      0  
5              20           90        3       20      26000    2088000      1  
...           ...          ...      ...      ...        ...        ...    ...  
996             7           76       20       10      44800    1618800      1  
997            28           53       10       24     963200    1144800      1  
998            72           35        8        7     914400     269500      0  
999            54            6        1       17     847800     126000      0  
1000           56           39       13       23     565600    1267500      1  

[1000 rows x 14 columns]

In [70]:
df[df.Product==151]

ID Gender  Age Region  Product  Price  Quantity_19  Quantity_20  \
1     784      F   72     제주      151   6700           84           89   
34    929      M   31     울산      151  33800            5           51   
353   264      F   18     광주      151  47800           65           96   
354   282      M   25     대구      151  47100           75           80   
584   100      M   38     서울      151  41200           80           36   
...   ...    ...  ...    ...      ...    ...          ...          ...   
9355  617      M   53     인천      151  11100           84           35   
9528  360      M   29     경기      151  27000           69           49   
9897   26      M   48     세종      151   4100           95           73   
9913  163      M   28     서울      151  42400            1           50   
9952  955      F   80     광주      151  10100           44           44   

      Time_19  Time_20  Amount_19  Amount_20  Sales  
1          18       13     562800     596300  구매 증가  
34          2       23     169000    1723800  구매 증가  
353        10       10    3107000    4588800  구매 증가  
354        21       19    3532500    3768000  구매 증가  
584        18       19    3296000    1483200  구매 감소  
...       ...      ...        ...        ...    ...  
9355       12       17     932400     388500  구매 감소  
9528        6       13    1863000    1323000  구매 감소  
9897       14       23     389500     299300  구매 감소  
9913       17        9      42400    2120000  구매 증가  
9952       17        4     444400     444400  구매 감소  

[103 rows x 13 columns]

[과제] 아래 가이드에 따라서 고객 구매데이터를 생성하고 데이터프레임으로 변환하여 출력하세요(관측치 1000개)

- id : 1 ~ 1000번 일련번호
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성
- product_19 : 제품코드 11111 ~ 99999
- product_20 : 제품코드 11111 ~ 99999
- price_19 : 1000 ~ 50000 사이 실수 난수 생성
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_19 : 1 ~ 100 사이 정수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- time_19 : 01 ~ 24 사이 정수 난수 생성
- time_20 : 01 ~ 24 사이 정수 난수 생성
- amount_19 : price_19 * quantity_19
- amount_20 : price_20 * quantity_20
- sales : 19년 대비 20년구매금액이 증가면 1, 감소면 0

In [6]:
sample=1000

arr = np.zeros((sample, 15))
columns = ['ID', 'Gender', 'Age', 'Region', 'Product_19', 'Product_20', 'Price_19', 'Price_20', 'Quantity_19', 'Quantity_20',
           'Time_19', 'Time_20', 'Amount_19', 'Amount_20', 'Sales']
index = [np.arange(1, sample+1)]
# price= np.random.randint(1,1000,sample)*100

df = pd.DataFrame(arr, index, columns=columns)
df.ID = np.random.randint(1, 1000, sample)
df.Gender = np.random.choice(['M', 'F'], sample)
df.Age = np.random.randint(10, 81, sample)
df.Region = np.random.choice(['서울', '부산', '인천', '대구', '대전', '광주', '울산', '세종', '경기', '제주'], sample)
df.Product_19 = np.random.randint(1000, 50001, sample)
df.Product_20 = np.random.randint(1000, 50001, sample)
df.Price_19 = np.random.randint(10,501,sample)*100
df.Price_20 = np.random.randint(10,501,sample)*100
df.Quantity_19 = np.random.randint(1, 101, sample)
df.Quantity_20 = np.random.randint(1, 101, sample)
df.Time_19 = np.random.randint(1, 25, sample)
df.Time_20 = np.random.randint(1, 25, sample)
df.Amount_19 = df.Price_19 * df.Quantity_19
df.Amount_20 = df.Price_20 * df.Quantity_20
df.Sales = np.where(df.Amount_20>df.Amount_19, '구매 증가', '구매 감소')
df

ID Gender  Age Region  Product_19  Product_20  Price_19  Price_20  \
1     489      M   14     인천       20356        4206    371000    243000   
2     232      M   39     세종       12528       13915    441000    407000   
3     908      M   41     대전       38199        7715     11000    423000   
4     952      F   51     대전       34506        1855    118000    324000   
5     447      M   73     제주       25017       38257    384000    130000   
...   ...    ...  ...    ...         ...         ...       ...       ...   
996   851      F   21     인천       36519       13161    329000    388000   
997   457      F   48     인천        6862       18067    392000      8000   
998   336      M   72     광주       25846       46586    108000     71000   
999   558      F   49     대구       37096       44151     21000     21000   
1000  344      M   36     대구       43883       47170    433000     16000   

      Quantity_19  Quantity_20  Time_19  Time_20  Amount_19  Amount_20  Sales  
1              39           59       15        7   14469000   14337000  구매 감소  
2               1           38       17       11     441000   15466000  구매 증가  
3              66           32       15       15     726000   13536000  구매 증가  
4              48           57        7        7    5664000   18468000  구매 증가  
5              49           89       10       16   18816000   11570000  구매 감소  
...           ...          ...      ...      ...        ...        ...    ...  
996            99            9       13       17   32571000    3492000  구매 감소  
997            23           22        5       17    9016000     176000  구매 감소  
998            79           99        1       11    8532000    7029000  구매 감소  
999            82           32        5        5    1722000     672000  구매 감소  
1000            3           84       21       23    1299000    1344000  구매 증가  

[1000 rows x 15 columns]