Numpy는 "Numerical Python"의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공
- Numerical Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
- 넘파이의 기본 데이터 타입은 ndarray.ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산을 수행

Numpy 특징
- 강력한 N차원 배열 객체
- 정교한 브로드캐스팅 기능
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 부내하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [1]:
!pip install numpy

In [4]:
import numpy as np

z = np.arange(10)
print(z, type(z))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [6]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [7]:
%time for _ in range(10): my_array2 = my_arr * 2

Wall time: 12 ms


In [8]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

Wall time: 611 ms


In [11]:
# 배열 연산
# np.random.randn = 가우시안 표준 정규분포(어떤 집합에 있어서 평균이 0, 표준편차가 1인 집합)에서 난수 매트릭스 array 생성

data = np.random.randn(2, 3) # 표준 정규분포로 구성되는 2행 3열 매트릭스
print(data, '\n')
print(data * 10, '\n')
print(data + data)

[[-1.19807407  0.47631157  0.99963931]
 [ 1.25182928  0.28661973 -1.70994904]] 

[[-11.98074073   4.76311567   9.99639306]
 [ 12.51829284   2.86619727 -17.09949038]] 

[[-2.39614815  0.95262313  1.99927861]
 [ 2.50365857  0.57323945 -3.41989808]]


In [13]:
print(data.shape) # 행렬의 크기 표현 (n행 n열)
print(data.dtype) # 데이터의 타입 (int, float, str...)
print(data.ndim) # 행렬의 차원

(2, 3)
float64


다차원 배열
<img src = 'numpy차원.jpg' STYLE='width:300px'>

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(type(data2), '\n')
arr2 = np.array(data2)
print(arr2, type(arr2))

<class 'list'> 

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [16]:
print(arr2.ndim, '\n')
print(arr2.shape)

2 

(2, 4)


In [17]:
# 1차원 배열로 3개의 데이터

array1 = np.array([1, 2, 3])
print(array1, type(array1), array1.shape) # (,열)이 아닌 (열,) 형태로 출력 / 튜플 형태기 때문

[1 2 3] <class 'numpy.ndarray'> (3,)


In [19]:
# 2차원 배열로 2개의 row와 3개의 column으로 구성된 6개의 데이터

array2 = np.array([[1, 2, 3], [4, 5, 6]])
print(array2, type(array2), array2.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [20]:
# 1개의 row와 3개의 column으로 구성된 2차원 배열

array21 = np.array([[1, 2, 3]])
print(array21, array21.shape)

[[1 2 3]] <class 'numpy.ndarray'> (1, 3)


In [22]:
# 3차원

array3 = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
                   [['a', 'b', 'c', 'd', 'e'], ['f', 'g', 'h', 'i', 'j']],
                   [['ㄱ', 'ㄴ', 'ㄷ', 'ㄹ', 'ㅁ'], ['ㅂ', 'ㅅ', 'ㅇ', 'ㅈ', 'ㅊ']]])
print(array3, array3.shape, type(array3))

[[['1' '2' '3' '4' '5']
  ['6' '7' '8' '9' '10']]

 [['a' 'b' 'c' 'd' 'e']
  ['f' 'g' 'h' 'i' 'j']]

 [['ㄱ' 'ㄴ' 'ㄷ' 'ㄹ' 'ㅁ']
  ['ㅂ' 'ㅅ' 'ㅇ' 'ㅈ' 'ㅊ']]] (3, 2, 5) <class 'numpy.ndarray'>


In [23]:
# 경고 메시지 제외 처리

import warnings
warnings.filterwarnings('ignore')

배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [29]:
print(np.zeros(10), '\n')
print(np.zeros((3, 6)), '\n')
print(np.zeros((2, 3, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [28]:
print(np.ones((2, 3, 2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [31]:
# full: n행 n열 배열을 _로 채우는 것

ar1 = np.full((2, 2), 5)
print(ar1)

[[5 5]
 [5 5]]


In [32]:
# 항등행렬, 단위행렬

ar2 = np.eye(3)
print(ar2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
# [과제] zeros_like, ones_like, full_like 함수 사용 예 작성

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print()

ar1 = np.zeros_like(a)
ar2 = ar1.astype(float)
print(ar2, ar2.dtype)
print()

ar3 = np.ones_like(a)
ar4 = ar3.astype(float)
print(ar4, ar4.dtype)
print()

ar5 = np.full_like(a, 6)
ar6 = ar5.astype('float32')
print(ar6, ar6.dtype)
print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] float64

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]] float32



In [34]:
# arange 함수 : python의 range 함수의 배열 버전

arr1 = np.arange(15)
# arr1 = range(15) # 배열 생성되지 않음 / (0, 15)의 범위튜플만 생성
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
arr2 = arr1.reshape(3, 5)
print(arr2, '\n')
arr3 = arr1. reshape(1, 3, 5)
print(arr3, arr3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]] (1, 3, 5)


In [42]:
# 연습문제 - array1에 reshape 함수를 이용, (5, 2) 배열을 생성하고 크기를 같이 출력

array1 = np.arange(10)

array2 = array1.reshape(5, 2)
print(array2, array2.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)


In [45]:
# 연습문제 - 0~29 일차원 배열을 생성한 후 다시 2, 3차원 배열로 변혼하여 출력

array1 = np.arange(30)

print(array1.reshape(6, 5), '\n')
print(array1.reshape(3, 2, 5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [48]:
# reshape(-1, -1) 이용, 차원 변경
# -1: 임의로 조정

array1 = np.arange(30)
ar12 = array1.reshape(5, -1)
print(ar12, ar12.shape, '\n')
ar13 = array1.reshape(-1, 2, 5)
print(ar13, ar13.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] (5, 6) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5)


In [53]:
# 2 -> 1, 3차원으로 변환하여 출력

ar12
print(ar12.reshape(-1,), '\n')
print(ar12.reshape(-1, 2, 5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [56]:
# 3 -> 1, 2차원으로 변환하여 출력

ar13
print(ar13.reshape(-1,), '\n')
print(ar13.reshape(-1, 5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


행렬의 종류
- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 항등핼렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을 때 항등행렬이 나오는 행렬

In [59]:
# 정방행렬

arr = np.full((5, 5), 7)
print(arr)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [60]:
# 항등행렬, 단위행렬

arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [66]:
# 영행렬

arr = np.zeros(25)
print(arr.reshape(5, 5))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


ndarray 데이터 형태 지정 및 변경
<img src = '데이터형태.jpg' STYLE='width:300px;'>

In [67]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype = np.int32)
print(arr1, arr1.dtype, '\n')
print(arr2, arr2.dtype)

[1. 2. 3.] float64 

[1 2 3] int32


In [71]:
# 타입 변경

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [73]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [86]:
# empty 함수: shape와 dtype을 입력 받아 초기화되지 않은 배열을 만들어준다. cf. zeros 함수
# empty 함수를 실행할 때마다 값이 다른 것을 확인할 수 있다. 이는 해당 메모리 영역에 어떤 데이터가 남아있던지 상관없이
# 그대로 영역의 주소만 알려줄 뿐 초기화는 사용자에게 맡기기 때문임.

print(np.empty(shape=(10,), dtype=np.int8)) # 이미 메모리에 존재하는 데이터로 배열 생성
print(np.zeros(shape=(10,), dtype=np.int8)) # 초기화하여 배열 생성

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


In [90]:
# 문자열 타입으로 배열 만들기

# arr = np.array([1, 2, 3, 4], dtype='S')
arr = np.array([1, 2, 3, 4], dtype = np.string_)
print(arr, arr.dtype)

[b'1' b'2' b'3' b'4'] |S1


In [85]:
arr1 = arr.astype(float) # 기본이 float64기 때문
# arr1 = arr.astype('float32')
print(arr1, arr1.dtype)

[1. 2. 3. 4.] float64


In [91]:
# 정수와 실수로 구성된 list_e = [1.2, 2.3, 3]을 numpy를 이용해서 실수형과 정수형으로 각각 출력

list_e = [1.2, 2.3, 3]

array_e1 = np.array(list_e)
print(array_e1, array_e1.dtype, '\n')

array_e2 = array_e1.astype(int)
print(array_e2, array_e2.dtype)

[1.2 2.3 3. ] float64 

[1 2 3] int32


In [94]:
# 배열의 산술 연산

# arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.arange(1, 7).reshape(2, 3)
print(arr, arr.dtype)

[[1 2 3]
 [4 5 6]] int32


In [95]:
arr * arr # 같은 위치에 있는 것끼리 곱셈

array([[ 1,  4,  9],
       [16, 25, 36]])

In [96]:
arr - arr # 같은 위치에 있는 것끼리 뺄셈

array([[0, 0, 0],
       [0, 0, 0]])

In [97]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [98]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [109]:
# 기본 사칙연산

value1 = np.arange(1, 10).reshape(3, 3)
value2 = np.arange(11, 20).reshape(3, 3)

print(value2 + value1, '\n')
print(np.add(value2, value1), '\n\n')

print(value2 - value1, '\n')
print(np.subtract(value2, value1), '\n\n')

print(value2 * value1, '\n')
print(np.multiply(value2, value1), '\n\n')

print(value2 / value1, '\n')
print(np.divide(value2, value1), '\n\n')

[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[12 14 16]
 [18 20 22]
 [24 26 28]] 


[[10 10 10]
 [10 10 10]
 [10 10 10]] 

[[10 10 10]
 [10 10 10]
 [10 10 10]] 


[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 


[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]] 

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]] 




In [129]:
arr = np.random.randn(2, 2)
arr

array([[ 0.52739866, -0.82461019],
       [ 0.53849778, -0.0836818 ]])

In [126]:
arr.mean().round(4)

-0.0681

In [130]:
arr.mean(axis=1) # 행 평균

array([-0.14860577,  0.22740799])

In [131]:
arr.mean(axis=0) # 열 평균

array([ 0.53294822, -0.454146  ])

In [132]:
arr.sum().round(4)

0.1576

In [133]:
arr.cumprod()

array([ 0.52739866, -0.43489831, -0.23419177,  0.01959759])

In [135]:
# 인덱싱, 슬라이싱

arr2d = np.arange(1, 10).reshape(3, 3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
arr2d[2][2]

9

In [141]:
arr2d[:, 0]

array([1, 4, 7])

In [158]:
arr2d[:2, :]
# arr2d[[0, 2], :] # 0, 2 행, 모든 열 출력

array([[1, 2, 3],
       [4, 5, 6]])

In [156]:
# arr2d에서 [3, 6], [[1, 2], [4, 5]]을 출력

print(arr2d[:2, 2])
print(arr2d[:2, :2])

[3 6]
[[1 2]
 [4 5]]


In [159]:
arr = np.arange(30).reshape(5, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [178]:
print(arr[2][2:5])
print(arr[[0, 1],3])
print(arr[:3, 1])

[14 15 16]
[3 9]
[ 1  7 13]


In [182]:
# 배열을 리스트로 변환

li = arr.tolist()
print(li, type(li))

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29]] <class 'list'>


In [186]:
# Boolean indexing

arr1d = np.arange(1, 10)
print(arr1d)
arr3 = arr1d[arr1d>5] # 조건에 맞는 것은 true, 맞지 않는 것은 false로 true인 것만 저장
print(arr3)
print(arr1d>5)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[False False False False False  True  True  True  True]


In [187]:
# arr1d에서 일반 인덱스를 이용해서 [6, 7, 8, 9] 출력

print(arr1d[5:])

[6 7 8 9]


In [193]:
# 연습문제 - 1 ~ 14 ndarray를 만들어 array_e로 저장하고 (array_e / 2) > 5를 만족하는 값을 불린 인덱싱으로 출력

array_e = np.arange(1, 15)
# print(array_e / 2 > 5)

array = array_e[(array_e / 2) > 5]
print(array)

[11 12 13 14]


In [211]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

print(names, '\n')
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] 

[[-0.4763729   0.98183395  0.33654586 -0.01370388]
 [-0.28843328  0.1497836   0.03520114  0.60740693]
 [-0.82389244 -0.40819936 -1.02699469  0.79460177]
 [ 0.84284764  0.63482795 -0.99760364  0.78075436]
 [ 0.79813896 -0.87565696  1.27412287  1.23993281]
 [-0.68083747 -1.18121484 -0.09390995 -0.29950933]
 [-0.3919429  -0.81010007  0.2775935  -0.91293963]]


In [212]:
names == 'Bob' # 0 번째, 3 번째 인덱스가 True

array([ True, False, False,  True, False, False, False])

In [213]:
data[names == 'Bob'] # 0 번째 3 번째 인덱스(True 인덱스) 출력

array([[-0.4763729 ,  0.98183395,  0.33654586, -0.01370388],
       [ 0.84284764,  0.63482795, -0.99760364,  0.78075436]])

In [214]:
data[names == 'Bob', 2:] # 0, 3번째 행 / 2: 번째 열

array([[ 0.33654586, -0.01370388],
       [-0.99760364,  0.78075436]])

In [215]:
# !=: 부정

data[names != 'Bob']

array([[-0.28843328,  0.1497836 ,  0.03520114,  0.60740693],
       [-0.82389244, -0.40819936, -1.02699469,  0.79460177],
       [ 0.79813896, -0.87565696,  1.27412287,  1.23993281],
       [-0.68083747, -1.18121484, -0.09390995, -0.29950933],
       [-0.3919429 , -0.81010007,  0.2775935 , -0.91293963]])

In [216]:
# Bob이거나 Will인 것 출력

mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[-0.4763729 ,  0.98183395,  0.33654586, -0.01370388],
       [-0.82389244, -0.40819936, -1.02699469,  0.79460177],
       [ 0.84284764,  0.63482795, -0.99760364,  0.78075436],
       [ 0.79813896, -0.87565696,  1.27412287,  1.23993281]])

In [220]:
# 음수를 모두 0으로 처리하여 출력

data[data<0]=0
print(data)

[[0.         0.98183395 0.33654586 0.        ]
 [0.         0.1497836  0.03520114 0.60740693]
 [0.         0.         0.         0.79460177]
 [0.84284764 0.63482795 0.         0.78075436]
 [0.79813896 0.         1.27412287 1.23993281]
 [0.         0.         0.         0.        ]
 [0.         0.         0.2775935  0.        ]]


In [228]:
# [과제] 1 ~ 100 정수에서 3의 배수인 것만 출력 (for문과 배열 두 가지 방식)

# for문
ret = []
for i in range(1, 101):
    if(i%3 == 0):
        ret.append(i)
print(ret)

print()

# 배열
arr = np.arange(1, 101)
print(arr[arr%3==0])

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [233]:
# [과제] 1 ~ 100 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두 가지 방식)

# for문
ret = []
for i in range(1, 101):
    if(i%5==0 and i%2==0):
        ret.append(i)
print(ret)

print()

# 배열
arr = np.arange(1, 101)
print(arr[(arr%5==0) & (arr%2==0)])

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

[ 10  20  30  40  50  60  70  80  90 100]


In [7]:
# [과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차

data = np.random.randn(5, 5)
print(data, '\n')

# 평균
print(data.mean())
# 표준편차
print(data.std())

[[ 0.39844089  0.63892057  1.13691882  0.53992135  0.37668649]
 [ 0.79816553 -0.56097408  1.61993119 -1.42349187 -0.25235849]
 [ 1.38273851 -0.36029778  0.03894657  1.12284366 -0.20080339]
 [-0.01167598  0.26903037 -1.27019615 -0.43106201 -0.77649341]
 [-0.67845263  0.64532618  0.2238584  -0.43116984 -0.23756755]] 

0.10228741511247184
0.7664363681793741


In [240]:
# [과제] 현재 사용하고 있는 numpy의 버전 출력

import numpy

print(numpy.__version__)

1.21.2


In [9]:
# [과제] numpy 함수의 도움말 기능을 볼 수 있는 방법을 수행하여 add 함수의 가이드 출력

# help(numpy.add)
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [11]:
# [과제] zeros 함수를 이용해서 아래와 같이 출력
# array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
# [과제] 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

lt = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(lt[::-1])

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [15]:
# [과제] [1, 2, 0, 0, 4, 0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.

arr = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(arr)) # 값이 0가 아닌 '인덱스'를 반환

(array([0, 1, 4], dtype=int64),)


In [17]:
# Fancy Indexing

arr = np.empty((8, 4))
print(arr)
for i in range(8):
    arr[i]=i
print(arr)

[[6.23042070e-307 1.69118108e-306 1.33511018e-306 1.33511969e-306]
 [6.23037996e-307 1.69121639e-306 1.20160575e-306 1.24610383e-306]
 [1.69118108e-306 8.06632139e-308 1.20160711e-306 1.69119330e-306]
 [8.01095173e-307 2.22522597e-306 9.34611148e-307 1.60220393e-306]
 [1.42417221e-306 1.95820216e-306 1.42417629e-306 1.95820216e-306]
 [1.86919513e-306 9.34604358e-307 9.34598925e-307 6.89807867e-307]
 [1.42417901e-306 6.23059386e-307 9.34598926e-307 8.01091099e-307]
 [6.89807188e-307 9.34601642e-307 1.42410974e-306 6.14415156e-144]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [18]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [19]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [21]:
arr = np.arange(32).reshape((8, 4))

print(arr, '\n')

arr[[1, 5, 7, 2], [0, 3, 1, 2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 



array([ 4, 23, 29, 10])

In [22]:
print(arr[[1, 5, 7, 2]],'\n')
print(arr[[1, 5,7, 2]][:, [0, 3, 1, 2]])

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]] 

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [23]:
# 배열 전치와 축 바꾸기

arr = np.arange(15).reshape(3, 5)
print(arr, '\n')
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
